#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLES: Statistics
#+DATE: <2017-05-10 Wed>
#+AUTHORS: weiwu
#+EMAIL: victor.wuv@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)


* Statistical Learning

** what is statistical learning

** assessing model accuracy

* Linear Regression

** Simple Linear Regression

** Multiple Linear Regression

* Classification

** Logistic Regression

** Linear Discriminant Analysis

** Comparison

* Resampling Methods

** Cross-Validation

** The Bootstrap

* Tree-Based Methods

** Decision Trees

** Bagging, Random Forests, Boosting

* Support Vector Machine
Support vector machines (SVMs) are a set of related supervised learning methods used for classification and regression. Given a set of training examples, each marked as belonging to one of two categories, an SVM training algorithm builds a model that predicts whether a new example falls into one category or the other.

** Maximal Margin Classifier

** Support Vector Classifiers

** Support Vector Machines

* Unsupervised Learning

** Principal Components Analysis

** Clustering Methods
Cluster analysis is the assignment of a set of observations into subsets (called clusters) so that observations within the same cluster are similar according to some predesignated criterion or criteria, while observations drawn from different clusters are dissimilar. Different clustering techniques make different assumptions on the structure of the data, often defined by some similarity metric and evaluated for example by internal compactness (similarity between members of the same cluster) and separation between different clusters. Other methods are based on estimated density and graph connectivity. Clustering is a method of unsupervised learning, and a common technique for statistical data analysis.

*** K-Means Clustering

*** Hierarchical Clustering
