#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+TITLES: alpha
#+DATE: <2018-08-16 Thu>
#+AUTHORS: weiwu
#+EMAIL: victor.wuv@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)
#+SETUPFILE: ../configOrg/level1.org
#+OPTIONS: title:t toc:t todo:t |:t


* Alpha design
A price action is a response to some world event. This event is reflected in the data. If the data never changes then there is no alpha. Thus, it is changes in the data that have the information. A change in information should produce a change in the alpha.

** QUALITY OF AN ALPHA
An alpha is considered one of good quality when:
The idea and expression is simple.
The expression/code is elegant.
It has good in-sample Sharpe.
It is not sensitive to small changes in data and parameters.
It works in multiple universes.
It works in different regions.
Its profit hits a recent new high.

** ALGORITHM FOR FINDING ALPHAS
Repeat the below steps forever:
Look at the variables in the data.
Get an idea of the change you want to model.
Come up with a mathematical expression that translates this change into stock position.
Test the expression.
If the result is favorable, submit the alpha.

** Categories:
According to the time the alphas use the information, and the frequency at which the predictions are generated, we may categorize those alphas into the following groups:
1. Intraday alphas: rebalanced during trading hours of the day. They can also be grouped as
follows:
a. Rebalance at each interval, e.g. 1 min/5 min/15 min, etc.
b. Rebalance triggered by some events such as ticks/orders/fills or predefined events.

2. Daily alphas: rebalance every day. These types of alphas can be broken into further
subgroups by the time the information is used:
a. Delay N: use data of N days ago.
b. Delay 0 snapshot: use the data before a certain time snapshot.
c. MOO/MOC: alphas trade at market open/close auction session.
3. Weekly/monthly alphas, rebalanced every week/month.

** DEVELOPMENT OF AN ALPHA
An alpha is developed by using public information. The more efficient the process, the better performance the alpha can achieve. One can find alphas either by sourcing public information or building specific models to process the information. Alphas can be generated by searching signals/patterns from the informational spaces. Typical sources are as follows:
1. Price/volume. We can use technical analysis or prediction/regression models based on the price/volume.
2. Fundamentals. By analyzing the fundamentals of each company automatically, one can build fundamental alphas. Such alphas typically have very low turnover.
*anormally*
3. Macro data, such as gross domestic product numbers, employment rates. Such numbers
have big impacts on the financial markets.
4. Text, such as Federal Open Market Committee minutes, company filings, papers, journals,
news, or even information in publicly available social media. It’s necessary to quantify the
text into numbers (eventually number of shares to buy/sell). Text data includes both current
and future events.
5. Multimedia such as videos/audios can also be used as information sources. The techniques
to process video/audio are pretty mature. For example, one can simply use Text-To-Speech
techniques to extract text information from the video/audio and then build models on the
text information.
Sometimes alphas are not derived from the models of information directly. This information
may be used to improve the performance of alphas or generate alphas. Some examples are
listed below:
1. Risk factor models: by controlling risk exposure or eliminating risk exposure to some
factors, one can improve the alpha’s performance.
2. Relationship models: e.g. instruments typically correlated with each other to some extent.
Some may lead or lag with others, thus they generate the opportunities for arbitrage.
3. Microstructure models to improve the execution performance of real trading.

** FUTURE PERFORMANCE
All of the measurements in the preceding section are intended to compare two alphas where
we have no additional information other than their actual predictions. However, additional
information, such as how the alpha was constructed, can yield useful information in
determining whether the alpha will make good predictions going forward. Ultimately, what is
important is whether the alpha makes reliable future predictions, not historical predictions.

Comparison of in-sample to out-of-sample performance is useful not only on the alpha level
but also in aggregate across all alphas of a given designer, or on groups of alphas from a given
designer.
