#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLES: MultiFactorModel
#+DATE: <2017-05-26 Fri>
#+AUTHORS: weiwu
#+EMAIL: victor.wuv@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)

* terms:
- ad hoc
specific.
- excess return
return relative to the risk-free return.
$r = r_a - r_f$
- expected return
- active return
return relative to a benchmark.
- alpha
expeced residual return, or expected exceptional return, or realized residual, or exceptional return.

residual return plus benchmark timing return.
$\Theta = \beta*(residual return + benchmark return exceeds consensus expected return)$
* Capital Asset Pricing Model
- measure systematic risk, it depends only upon exposure to the overall market, usually proxied by a broad stock market index, such as the S&P 500. This exposure is measured by the CAPM beta.
- capital asset pricing model (CAPM) is a model used to determine a theoretically appropriate required rate of return of an asset, to make decisions about adding assets to a well-diversified portfolio.
- Only by exposing a well-diversified portfolio to higher market risk can an investor expect to achieve a higher rate of return.(SML) *What is the appropriate measure of risk?*
- Beta, the coefficient of the independent variable (the market's rate of return) in an ordinary least squares regression equation to explain the dependent variable (a security's rate of return), measures a security's relative amount of systematic (market) risk.


- The return of any stock can be separated into a systematic (market) component and a residual component. No theory is required to do this.
- The CAPM says that the residual component of return has an expected value of zero.
- The CAPM is easy to understand and relatively easy to implement.
- There is a powerful logic of market efficiency behind the CAPM.
- The CAPM thrusts the burden of proof onto the active manager. It suggests that passive management is a lowerrisk alternative to active management.
- The CAPM provides a valuable source of consensus expectations. The active manager can succeed to the extent that his or her forecasts are superior to the CAPM consensus forecasts.
- The CAPM is about expected returns, not risk.
** overview
- The model takes into account the asset's sensitivity to non-diversifiable risk (also known as systematic risk or market risk), often represented by the quantity beta (β) in the financial industry, as well as the expected return of the market and the expected return of a theoretical risk-free asset.
- $r_a = r_f + \beta (r_m - r_f)$
 rm(t) is the return (in time period t) on a market index, such as the
S&P500.
\beta = cov[r,(t), rm(t)]/var[rm(t)
- The CAPM is equivalent to the statement that the market index is itself mean-variance efficient in the sense of providing maximum average return for a given level of volatility.
** breaking down
- two factors: time value of money and risk.
- individual risk premium equals the market premium times beta.
** forecast of expected return
*** problem of using historical average returns
 One alternative is to use historical average returns, i.e., the average return to the stock over some previous period. This is not a good idea, for two main reasons.
- First, the historical returns contain a large amount of sample error.
- Second, the universe of stocks changes over time: New stocks become available, and old stocks expire or merge. The stocks themselves change over time: Earnings change, capital structure may change, and the volatility of the stock may change. Historical averages are a poor alternative to consensus forecasts.

* Arbitrage Pricing Theory

** overview
-  only one type of nondiversifiable risk influences expected security returns, and that single type of risk is *market risk.*
- the APT recognizes that several different broad risk sources may combine to influence security returns. The intuitive appeal of the APT results from its recognition that the interaction of several macroeconomic factors such as *inflation, interest rates, and business activity* affects rates of return.
- A series of beta coefficients are estimated to measure the sensitivity to the respective factor risks for a particular security.

** shortfalls or using accounting attributes as market risk:
- Most are based on accountingdata, and such data are generated by rules that may differ sigmficantly across firms.
- Even if allfirms used the same accountingrules, reporting dates differ, so constructing time-synchronized interfirm comparisons is difficult.
- Most importantly, no rigorous theory tells us how traditional accounting variables should be related to an appropriate measure of risk for computing the risk-return trade-off.

** Basics:
- Every stock and portfolio has exposures (or betas) with respect to each of these systematic risks. The pattern of economic betas for a stock or portfolio is called its risk exposure profile.

*** APT Equations
The APT follows from two basic postulates:

**** Postulate 1.
In every time period, the difference between the actual (realized)return and the expected return for any asset is equal to the sum, over all risk factors, of the risk exposure (the beta for that risk factor) multiplied by the realization (the actual end-of-period value) for that risk factor, plus an asset-specific (idiosyncratic) error term.
$$r_i(t) - E[r_i(t)] = \beta_i1 f_1(t) + ... + \beta_iK f_K(t) + \epsilon_i(t)$$
- It is assumed that the expectations, at the beginning of the period, for all of the factor realizations and for the asset-specific shock are zero;
$$E[f_1(t)] = ... = E[f_K(t)] = E[\epsilon_i(t)] = 0$$

**** Postulate 2.
Pure arbitrage profits are impossible.
$$E[r_i(t)] = P_0 + \beta_i1 P_1 + ... + \beta_iK P_K$$
$$r_i(t) - P_0  = \beta_i1 [P_1 + f_1(t)] + ... + \beta_iK[P_K + f_K(t)] + \epsilon_i(t)$$
* Active Portfolio Management
** benchmark portfolio
** exceptional returns relative to benchmark
** trade off forecasts of exceptional return against additional risk
** process of active management
*** processing of raw signals into exceptional return forecasts
*** portfolio construction, trading, performance analysis
*** asset selection, asset allocation, benchmark timing
** forecasting
*** superior information
if your forecasts match the consensus, or your forecasts differe from the consensus but contain no information, this machinery will lead you back to the benchmark.

only as you develop superior information will your portfolio deviate from the benchmark.
** success relies on breath and skill
** mathematics cannot overcome ignorance, half-life
how to evaluating the horizon value of information.
** where to look for superior information
*** forecasting factor returns
*** forecasting asset specific return
*** information sources that have proven valuable in the past
** Applications
*** Structure model 1: Given Exposure, estimate factor returns
*** Structure model 2: Given Factor returns, estimate exposures.
*** Statistical Model 1: Principal Components Analysis
use the principal components to explain the other stocks, the historical return are already known, use this as the factors, then calculate the coefficients.
*** Statistical Model 2: Maximum Likeliood factor analysis
** Valuation from cash flows
Risk-adjusted expectations:

the modern theory of valuation prices uncertain future cash flows by risk-adjusting the expected cash flows and discounting them to the present using the risk-free rate.
*** Valuation of equities
the standard quantitative method is the dividend discount model, which focuses on dividends, earnings, and growth.

Dividend discount model is only as good as their growth forecasts.

The goal of valuation is trying to find those equities which are mispriced and to make money when the price is corrected by the market.
** Valuation in practice
stock value = financial value + operational value


* One factor model
associated with the Capital Asset Pricing Model (CAPM).

* Multi-Factor Model
** What is a 'Multi-Factor Model'
A multi-factor model is a financial model that employs multiple factors in its computations to explain market phenomena and/or equilibrium asset prices. The multi-factor model can be used to explain either an individual security or a portfolio of securities.
** Why a Multi-Factor Model?
Computing sample statistics directly from historical data, however, is fraught with danger.
- Weak signals
- noise aside,
- when a new asset enters the existing universe, there is no reliable way of calculating its relationships with the other assets,
- data points totalling no less than the number of assets are required to accurately estimate all the variances and covariances directly. Even with a universe of 100 assets, over 1 2 · 100 · (100+ 1) > 5; 000 relationships need to be estimated. For stock markets like the U.S. (over 12,000 assets), this becomes completely infeasible.
- A better approach is to first impose some structure on the asset returns by identifying common factors within the market | that is, factors which drive asset returns.

Factors used in multi-factor models can fall into several broad categories:
- Fundamental factors
  - Industry and country factors reflect a company’s line of business and country of domicile.
  - Style factors encapsulate the financial characteristics of an asset | a company’s size, debt levels, liquidity, etc. They are usually calculated from a mixture of market and fundamental (i.e. balance sheet) data.
  - Currency factors represent the interplay between local currencies of the various assets within the model.
  - Macroeconomic factors capture an asset’s sensitivity to variables such as GNP growth, bond yields, inflation, etc.

- Statistical factors
are mathematical constructs responsible for the observed correlations in asset returns. They are not directly connected to any observable real-world phenomena, and may change from one period to the next.

r = Bf + u

where r is the asset returns vector at time t, f is the factor return vector, u the set of asset specific returns.
** BREAKING DOWN 'Multi-Factor Model'
Multi-factor models are used to construct portfolios with certain characteristics, such as risk, or to track indexes.
** Categories of Multi-Factor Models
- Multi-factor models can be divided into three categories: macroeconomic models, fundamental models and statistical models.
- Macroeconomic models compare a security's return to such factors as employment, inflation and interest.
- Fundamental models analyze the relationship between a security's return and its underlying financials, such as earnings.
- Statistical models are used to compare the returns of different securities based on the statistical performance of each security in and of itself.
** Beta
The beta of a security measures the systemic risk of the security in relation to the overall market.
- A beta of 1 indicates that the security theoretically experiences the same degree of volatility as the market and moves in tandem with the market.
- A beta greater than 1 indicates the security is theoretically more volatile than the market.
- Conversely, a beta less than 1 indicates the security is theoretically less volatile than the market.
** Multi-Factor Model Formula
Ri = ai + _i(m) * Rm + _i(1) * F1 + _i(2) * F2 +...+_i(N) * FN + ei

Where:
- Ri is the returns of security i
- Rm is the market return
- F(1, 2, 3 ... N) is each of the factors used
- _ is the beta with respect to each factor including the market (m)
- e is the error term
- a is the intercept
** Fama and French Three-Factor Model
*** size of firms, SMB (small minus big)
SMB accounts for publicly traded companies with small market caps that generate higher returns
*** book-to-market values, HML (high minus low)
- HML accounts for values stocks with high book-to-market ratios that generate higher returns in comparison to the market.
- HML accounts for the spread in returns between value and growth stocks and argues that companies with high book-to-market ratios, also known as value stocks, outperform those with lower book-to-market values, known as growth stocks.

*** excess return on the market, portfolio's return less the risk free rate of return

** Fundamental Factor Model
| Style Factors                | Description                                                                                                   |
|------------------------------+---------------------------------------------------------------------------------------------------------------|
| 负债率因子暴露（mark-cap）   | Total debt to market capitalization                                                                           |
| 价值因子暴露（mark-cap）     | Book-to-price                                                                                                 |
| 短期动量因子暴露（mark-cap） | Cumulative return over past month                                                                             |
| 成长因子暴露（mark-cap）_L   | Plowback times return-on-equity                                                                               |
| 规模因子暴露（mark-cap）     | Natural logarithm of market capitalization                                                                    |
| 中期动量因子暴露（mark-cap） | Cumulative return over past year excluding most recent month                                                  |
| 换手率因子暴露（mark-cap）   | 1 month average daily volume over market capitalization                                                       |
| 波动率因子暴露（mark-cap）   | 3 month average of absolute return over cross-sectional standard deviation                                    |
|------------------------------+---------------------------------------------------------------------------------------------------------------|
| Industry Factors (32)        | GICS-based industry classification with 0/1 assignments.(see the additional AX-CN Further Results Appendix)   |

** Statistical Factor Model
| Factor Structure | 15 statistical factors                                                                          |
| Estimation       | 2-Pass Asymptotic Principal Components factor analysis with residual variance adjusted returns. |
|                  |                                                                                                 |

* Multi-Factor Risk Model
** why multi factor risk model and the usage
The asset covariance matrix is critical both for portfolio construction and for risk management purposes.
A key challenge in estimating the asset covariance matrix lies in the sheer dimensionality of the
problem. For instance, an active portfolio containing 2000 stocks multiplies 1000 days requires more than two million
independent elements. If the asset covariance matrix is computed *naively* — that is, by brute force —
then the matrix is likely to be extremely ill-conditioned. This makes the asset covariance matrix highly
susceptible to *noise and spurious* relationships that are unlikely to persist out-of-sample. For instance, if
the number of time observations is less than the number of stocks (as would be typical for large
portfolios), the matrix is said to be “rank deficient,” meaning that it is possible to construct apparently
riskless portfolios.

Factor risk models were developed to provide a more *robust* solution to this problem. Stock returns are
attributed to a factor component that affects all stocks, and an idiosyncratic component that is unique
to the particular stock.

Consider a *portfolio with weights $w_n$* , and return given by
$$R_P = \displaystyle\sum_{n} w_n r_n.$$

The portfolio factor exposures are given by the weighted average of the asset exposures, i.e.,
$$X_k^P = \displaystyle\sum_{n}w_n X_{nk}$$.
** structure
*** four components:
- a stock's exposures to the factors
- its excess returns
- the attributed factor returns
- the specific returns.
$$r_n(t) = \displaystyle\sum_{k} X_{n,k}f_k(t)+u_n(t)$$, where

$X_{n,k}$ = exposure of asset n to factor k.

$r_n(t)$ = the excess return(return above the risk free return) on stock n during the period from t to time t+1.

$f_k(t)$ = the factor return to factor k during the period from time t to time t + 1,

$u_n(t)$ = stock n's specific return during the period from time t to time t + 1. This is the return that cannot be explained by the factors.


*** risk structure:
$$ V_{n,m} = \displaystyle\sum_{k1,k2=1}^{K} X_{n,k1} F_{k1,k2} X_{m,k2} + \delta_{n,m} $$
where

$V_{n,m}$ = the covariance of asset n with asset m (if n = m, this gives the variance of asset n),

$X_{n,k1}$ = the exposure of asset n to factor k1,

$F_{k1,k2}$ = the covariance of factor k l with factor k2 (if k l = k2, this gives the variance of factor kl), and

$\delta_{n,m}$ = the specific covariance of asset n with asset m. By assumption, all specific risk correlations are zero, so this term is zero unless n = m. In that case, this term gives the specific variance of asset n.

** building the model

*** choosing the factors
all factors must be a priori factor. even though the factor returns are uncertain, the factor exposures must be known at the beginning of the period.
- The first source, due to factors, represents the systematic component.
- The second source represents the diversifiable component that cannot be explained by the factors, and is therefore deemed idiosyncratic or asset specific.
**** Responses to external influences
These factors include
- responses to return in the bond market (sometimes called bond beta)
- unexpected changes in inflation (iation surprise)
- changes in oil prices
- changes in exchange rates
- changes in industrial production
***** defects:
- the response coefficient has to be estimated through regression analysis or some similar technique. This requirement leads to errors in the estimates, commonly called the error-in-variables problem.
- the estimates are based on behavior during a past period, generally five years. Even if these past estimates are accurate in the statistical sense of capturing the true situation in the past, they may not accurately describe the present. In short, these response coefficients can be nonstationary.
- A key assumption underlying factor risk models is that the factors capture all systematic drivers of asset returns, thus implying that the specific returns are mutually uncorrelated.
- Another important characteristic of a high-quality factor structure is parsimony, meaning that the systematic component of asset returns is explained with the fewest possible number of factors.
***** key of success choosing factors
- statistical significance of the factor returns. In particular, the statistical significance of the factors should be persistent across time, and not due to isolated events that are unlikely to recur in the future.
- Stability is another characteristic of a high-quality factor structure. Stability means that typical stock exposures do not change drastically over short periods of time.
***** data preparation
multi-step algorithm to identify and treat outliers. The algorithm assigns each observation into one of three groups.
- The first group represents values so extreme that they are treated as potential data errors and removed from the estimation process.
- The second group represents values that are regarded as legitimate, but nonetheless so large that their impact on the model must be limited. We trim these observations to three standard deviations from the mean.
- The third group of observations, forming the bulk of the distribution, consists of values that are less than three standard deviations from the mean; these observations are left unadjusted.
**** cross-sectional comparisons of asset attributes
These factors, which have no link to the remainder of the economy, compare attributes of the stocks.
***** fundamental
- dividend yield
- earnings yield
- analysts' forecasts of future earnings per share
***** market
- volatility
- return during a past period
- option-implied volatility
- share turnover
**** purely internal or statistical factors
It is possible to amass returns data on a large number of stocks, turn the crank of a statistical meat grinder, and admire the factors the machine produces: factor ex machina.
methods:
- principal component analysis
- maximum likelihood analysis
- expectations maximization analysis
**** overall criteria:
- incisive
- intuitive
- interesting

*** estimating factor returns
**** exposures
***** industry exposures
The market itself has unit exposure in total to the industries. Because large corporations can do business in several industries, the industry factors must account for multiple industry memberships.
***** risk index exposures
- Volatilitydistinguishes stocks by their volatility. Assets that rank high in this dimension have been and are expected to be more volatile than average.
- Momentum distinguishes stocks by recent performance.
- Size distinguishes large stocks from small stocks.
- Liquidity distinguishes stocks by how often their shares trade.
- Growth distinguishes stocks by past and anticipated earnings growth.Value distinguishes stocks by their fundamentals, including ratios of earnings, dividends, cash flows, book value, and sales to price; is the stock cheap or expensive relative to fundamentals?
- Earnings volatility distinguishes stocks by their earnings stability.
- Financial leverage distinguishes firms by their debt-to-equity ratios and exposure to interest rate risk.
****** Relying on several different descriptors can improve model robustness.
****** all raw exposure data must be rescaled:
$$X_{normalized} = \frac{X_{raw} - mean(X_{raw})}{SD(X_{raw})}$$
**** returns
- Given exposures to the industry and risk index factors, the next step is to estimate returns via multiple regressions.
- The R2 statistic, which measures the explanatory power of the model, tends to average between 30 percent and 40 percent for models of monthly equity returns with roughly 1,000 assets and 50 factors. Larger R' statistics tend to occur in months with larger market moves.
- formly: least squares regressions, weighting each observed return by the inverse of its specific variance.
- Although these cross-sectional regressions can involve many variables (the USE2 model uses 68 factors), *the models do not suffer from multicollinearity.* Most of the factors are industries (55out of 68 in USEZ), which are orthogonal. In addition, tests of variance inflation factors, which measure the inflation in estimate errors attributable to multicollinearity, lie far below serious danger levels.
**** Factor Portfolios
$$f=(X^T W X)^{-1} (X^T W r)$$, where X is the exposure matrix, W is the diagonal matrix of regression weights, and r is the vector of excess returns.
$$f_k = \displaystyle\sum_{n=1}^{N} C_{k,n}r_n$$
***** Factor Covariance
Once the factor returns each period are estimated, we can estimate a factor covariance matrix-an estimate of all the factor variances and covariances.
***** Specific-Risk Matrixes
$u_n$, is that component of its return that the model cannot explain. So the multiple-factor model can provide no insight into stock-specific returns.

For specific risk, we need to model specific return variance, $u_n^2$ assuming that mean specific return is zero.

In general, the model for specific risk is
$$ u_n^2(t) = S(t)[1+v_n(t)]$$ with $$(1/N)\displaystyle\sum_{n=1}^{N} u_n^2(t) = S(t), (1/N)\displaystyle\sum_{n=1}^{N} v_n(t) = 0 $$
S(t) measures the average specific variance across the universe of stocks, and $v_n$ captures the cross-sectional variation in specific variance.
*** forecasting risk
we use a time series model for S(t) and a linear multiple-factor model for vn(t). Models for vn(t) typically include some risk index factors, plus factors measuring recent squared specific returns.
*** Data Requirements
**** stock returns
adjusted stock close price.
**** sufficient industry identification data to calculate factor exposures
- earnings
- sales
- assets segmented by industry
- historical returns
- associated option information
- fundamental accounting data
- earnings forecasts
** Model validity
three categories: in-sample tests, out-of-sample tests, and empirical observations.
*** in-sample tests
**** $R^2$ roughly 50 factors to explain the returns to roughly 1,000 assets each month.
Monthly R2statistics for the models average about 30-40 percent, meaning
that the model "explains," on average, about 30-40 percent of the observed
cross-sectional variance of the universe of stock returns.
- the R2 statistic can vary quite significantly from month to month, depending in part on the overall market return.
ModelR2statistics are highest when the market return differs very signdicantly
from zero. The R2statistic was very high in October 1987 because the market
return was so extreme. In months when the market return is near zero, the R2
statistic can be quite low, even if discrepancies between realized and modeled
returns are small
**** root mean square error from the regression.
*** out-of-sample tests
Out-of-sample tests compare forecast risk with realized risk.

One out-ofsample test builds portfolios of randomly chosen assets and then compares the forecast and realized active risk of those portfolios.
*** empirical observations
concerning model validity are more vague than statistical tests, but they are still relevant.
** Applications of Multiple-Factor Risk Model
- the attribution of asset returns to chosen common factor and specific returns,
- forecasts of the variances and covariances of these common factor and specific returns.
*** The Present: Current Portfolio Risk Analysis.
*** Portfolio Construction
risk-adjusted expected return:
$$ U = \displaystyle\sum_{n=1}^{N}h_n r_n - \lambda \displaystyle\sum_{n,m=1}^{N} h_n V_{n,m} h_m$$
$h_n$ is the holding of asset n, $r_n$ is the expected return to asset n, $\lambda$ is a risk aversion parameter. $V_{n,m}$ covariance coming from multiple-factor risk model.
*** Performance Analysis
** Factor Exposures

** Factor Returns
** Factor Covariance Matrix
** Specific Risk
* 量化选股

** 基本面选股

*** 多因子模型
优点是可以综合很多信息后给出一个选股结果. 综合因子的方法有打分法和回归法两种，打分法较为常见。

**** steps:

***** 备选因子选取

****** 估值：账面市值比（B/M)、盈利收益率（EPS）、动态市盈（PEG）

****** 成长性：ROE、ROA、主营毛利率（GP/R)、净利率(P/R)

****** 资本结构：资产负债（L/A)、固定资产比例（FAP）、流通市值（CMV）

***** 因子有效性检验
采用排序的方法检验备选因子的有效性。

*** 风格轮动模型

*** 行业轮动模型

** 市场行为选股

*** 资金流选股

*** 动量反转模型

*** 一致预期模型

*** 趋势追踪模型
