#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:auto timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLES: MultiFactorModel
#+DATE: <2017-05-26 Fri>
#+AUTHORS: weiwu
#+EMAIL: victor.wuv@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)


* Capital asset pricing model
- measure systematic risk, it depends only upon exposure to the overall market, usually proxied by a broad stock market index, such as the S&P 500. This exposure is measured by the CAPM beta.
- capital asset pricing model (CAPM) is a model used to determine a theoretically appropriate required rate of return of an asset, to make decisions about adding assets to a well-diversified portfolio.
- Only by exposing a well-diversified portfolio to higher market risk can an investor expect to achieve a higher rate of return.(SML) *What is the appropriate measure of risk?*
- Beta, the coefficient of the independent variable (the market's rate of return) in an ordinary least squares regression equation to explain the dependent variable (a security's rate of return), measures a security's relative amount of systematic (market) risk.

** overview
- The model takes into account the asset's sensitivity to non-diversifiable risk (also known as systematic risk or market risk), often represented by the quantity beta (β) in the financial industry, as well as the expected return of the market and the expected return of a theoretical risk-free asset.
- $r_a = r_f + \beta (r_m - r_f)$
 rm(t) is the return (in time period t) on a market index, such as the
S&P500.
\beta = cov[r,(t), rm(t)]/var[rm(t)
- The CAPM is equivalent to the statement that the market index is itself mean-variance efficient in the sense of providing maximum average return for a given level of volatility.
** breaking down
- two factors: time value of money and risk.
- individual risk premium equals the market premium times beta.

* Arbitrage Pricing Theory

** overview
-  only one type of nondiversifiable risk influences expected security returns, and that single type of risk is *market risk.*
- the APT recognizes that several different broad risk sources may combine to influence security returns. The intuitive appeal of the APT results from its recognition that the interaction of several macroeconomic factors such as *inflation, interest rates, and business activity* affects rates of return.
- A series of beta coefficients are estimated to measure the sensitivity to the respective factor risks for a particular security.

** shortfalls or using accounting attributes as market risk:
- Most are based on accountingdata, and such data are generated by rules that may differ sigmficantly across firms.
- Even if allfirms used the same accountingrules, reporting dates differ, so constructing time-synchronized interfirm comparisons is difficult.
- Most importantly, no rigorous theory tells us how traditional accounting variables should be related to an appropriate measure of risk for computing the risk-return trade-off.

** Basics:
- Every stock and portfolio has exposures (or betas) with respect to each of these systematic risks. The pattern of economic betas for a stock or portfolio is called its risk exposure profile.

*** APT Equations
The APT follows from two basic postulates:

**** Postulate 1.
In every time period, the difference between the actual (realized)return and the expected return for any asset is equal to the sum, over all risk factors, of the risk exposure (the beta for that risk factor) multiplied by the realization (the actual end-of-period value) for that risk factor, plus an asset-specific (idiosyncratic) error term.
$$r_i(t) - E[r_i(t)] = \beta_i1 f_1(t) + ... + \beta_iK f_K(t) + \epsilon_i(t)$$
- It is assumed that the expectations, at the beginning of the period, for all of the factor realizations and for the asset-specific shock are zero;
$$E[f_1(t)] = ... = E[f_K(t)] = E[\epsilon_i(t)] = 0$$

**** Postulate 2.
Pure arbitrage profits are impossible.
$$E[r_i(t)] = P_0 + \beta_i1 P_1 + ... + \beta_iK P_K$$
$$r_i(t) - P_0  = \beta_i1 [P_1 + f_1(t)] + ... + \beta_iK[P_K + f_K(t)] + \epsilon_i(t)$$
* One factor model
associated with the Capital Asset Pricing Model (CAPM).

* Multi-Factor Model
** What is a 'Multi-Factor Model'
A multi-factor model is a financial model that employs multiple factors in its computations to explain market phenomena and/or equilibrium asset prices. The multi-factor model can be used to explain either an individual security or a portfolio of securities.
** BREAKING DOWN 'Multi-Factor Model'
Multi-factor models are used to construct portfolios with certain characteristics, such as risk, or to track indexes.
** Categories of Multi-Factor Models
- Multi-factor models can be divided into three categories: macroeconomic models, fundamental models and statistical models.
- Macroeconomic models compare a security's return to such factors as employment, inflation and interest.
- Fundamental models analyze the relationship between a security's return and its underlying financials, such as earnings.
- Statistical models are used to compare the returns of different securities based on the statistical performance of each security in and of itself.
** Beta
The beta of a security measures the systemic risk of the security in relation to the overall market.
- A beta of 1 indicates that the security theoretically experiences the same degree of volatility as the market and moves in tandem with the market.
- A beta greater than 1 indicates the security is theoretically more volatile than the market.
- Conversely, a beta less than 1 indicates the security is theoretically less volatile than the market.
** Multi-Factor Model Formula
Ri = ai + _i(m) * Rm + _i(1) * F1 + _i(2) * F2 +...+_i(N) * FN + ei

Where:
- Ri is the returns of security i
- Rm is the market return
- F(1, 2, 3 ... N) is each of the factors used
- _ is the beta with respect to each factor including the market (m)
- e is the error term
- a is the intercept
** Fama and French Three-Factor Model
*** size of firms, SMB (small minus big)
SMB accounts for publicly traded companies with small market caps that generate higher returns
*** book-to-market values, HML (high minus low)
- HML accounts for values stocks with high book-to-market ratios that generate higher returns in comparison to the market.
- HML accounts for the spread in returns between value and growth stocks and argues that companies with high book-to-market ratios, also known as value stocks, outperform those with lower book-to-market values, known as growth stocks.

*** excess return on the market, portfolio's return less the risk free rate of return

* Multi-Factor Risk Model

** form
$$V_{n,m} = \displaystyle\sum_{k1,k2=1}^{K} X_{n,k1} F_{k1,k2} X_{m,k2} + \delta_{n,m}$$
where
$V_{n,m}$ = the covariance of asset n with asset m (if n = m, this gives the variance of asset n),
$X_{n,k1}$ = the exposure of asset n to factor k1,
$F_{k1,k2}$ = the covariance of factor k l with factor k2 (if k l = k2, this gives the variance of factor kl), and
$\delta_{n,m}$ = the specific covariance of asset n with asset m. By assumption, all specific risk correlations are zero, so this term is zero unless n = m. In that case, this term gives the specific variance of asset n.

** building the model

*** choosing the factors
all factors must be a priori factor. even though the factor returns are uncertain, the factor exposures must be known at the beginning of the period.
**** Responses to external influences
These factors include
- responses to return in the bond market (sometimes called bond beta)
- unexpected changes in inflation (iation surprise)
- changes in oil prices
- changes in exchange rates
- changes in industrial production
***** defects:
- the response coefficient has to be estimated through regression analysis or some similar technique. This requirement leads to errors in the estimates, commonly called the error-in-variables problem.
- the estimates are based on behavior during a past period, generally five years. Even if these past estimates are accurate in the statistical sense of capturing the true situation in the past, they may not accurately describe the present. In short, these response coefficients can be nonstationary.

**** cross-sectional comparisons of asset attributes
These factors, which have no link to the remainder of the economy, compare attributes of the stocks.
***** fundamental
- dividend yield
- earnings yield
- analysts' forecasts of future earnings per share
***** market
- volatility
- return during a past period
- option-implied volatility
- share turnover
**** purely internal or statistical factors
It is possible to amass returns data on a large number of stocks, turn the crank of a statistical meat grinder, and admire the factors the machine produces: factor ex machina.
methods:
- principal component analysis
- maximum likelihood analysis
- expectations maximization analysis
**** overall criteria:
- incisive
- intuitive
- interesting

*** estimating factor returns
**** exposures
***** industry exposures
***** risk index exposures
*** forecasting risk






* 量化选股

** 基本面选股

*** 多因子模型
优点是可以综合很多信息后给出一个选股结果. 综合因子的方法有打分法和回归法两种，打分法较为常见。

**** steps:

***** 备选因子选取

****** 估值：账面市值比（B/M)、盈利收益率（EPS）、动态市盈（PEG）

****** 成长性：ROE、ROA、主营毛利率（GP/R)、净利率(P/R)

****** 资本结构：资产负债（L/A)、固定资产比例（FAP）、流通市值（CMV）

***** 因子有效性检验
采用排序的方法检验备选因子的有效性。

*** 风格轮动模型

*** 行业轮动模型

** 市场行为选股

*** 资金流选股

*** 动量反转模型

*** 一致预期模型

*** 趋势追踪模型
