#+TITLES: Option
#+KEYWORDS: option
#+OPTIONS: H:2 toc:2 num:3 ^:nil
#+SETUPFILE: ../configOrg/level1.org
#+Latex: t


* Option

** definition

- call: right to purchase stocks at strike price.
- put: right to sell stocks at strike price.

** Option premium:
- premium = intrinsic value + time value
  1. Intrinsic value in options is the in-the-money portion of the option's premium. For example, if a call options strike price is $15 and the underlying stock's market price is at $25, then the intrinsic value of the call option is $10, or $25 - $15.
  2. Value of a call option: max[(S-K),0].
  3. Value of a put option: max[(K-S),0].
  4. the time value (TV) (extrinsic or instrumental value) of an option is the premium a rational investor would pay over its current exercise value (intrinsic value), based on the probability it will increase in value before expiry.

** Black Scholes vs Monte Carlo vs Binomial tree
*** Black Scholes:
known input factors such as time to expiration, volatility, interest rate, current stock price, strike price, dividend yield. It's based on risk neutral process under some reasonable assumptions.
- the underlying stock price follows a geometric Brownian motion
- The model is based on a normal distribution of underlying asset returns
- The option is European and can only be exercised at expiration
- No dividends are paid out during the life of the option
- Efficient markets (i.e., market movements cannot be predicted)
- There are no transaction costs in buying the option
- The risk-free rate and volatility of the underlying are known and constant
- That the returns on the underlying are normally distributed

**** Advantages & Limitations
***** Advantage: The main advantage of the Black-Scholes model is speed -- it lets you calculate a very large number of option prices in a very short time.

***** Limitation: The Black-Scholes model has one major limitation:  it cannot be used to accurately price options with an American-style exercise as it only calculates the option price at one point in time --  at expiration. It does not consider the steps along the way where there could be the possibility of early exercise of an American option.
*** Monte Carlo and binomial tree use numerical simulation procedures.
**** Advantages & Limitations
***** Advantage: The big advantage the binomial model has over the Black-Scholes model is that it can be used to accurately price American options.
***** Limitation:  The main limitation of the binomial model is its relatively slow speed.
** Greeks

*** delta
Option value change respected to the stock price change.

*** gamma
Option delta change respected to the stock price change.

*** theta
Option value change respected to the time to expiration.

*** rho
Option value change respected to the interest rate change.

*** vega
Option value change respected to the volatility change.

** Market microstructure and products

** Basics of vanilla option risk

** Risks of exotic options

** Option theory
* Future

*基差=现货价格-期货价格

*基差的不确定性被称为基差风险，降低基差风险实现套期保值关键是选择匹配度高的对冲期货合约。基差风险与对冲平仓时的基差直接相关，当投资者持有现货，持有期货短头寸对冲，对冲平仓日基差扩大，投资者将盈利；相反，当投资者未来将买入某项资产，持有期货长头寸对冲，对冲平仓日基差扩大，投资者将亏损。

*基差有时为正（此时称为反向市场），有时为负（此时称为正向市场），因此，基差是期货价格与现货价格之间实际运行变化的动态指标。
反向市场（又称逆向市场Inverted Market或现货溢价Backwardation）是指在特殊情况下，现货价格高于期货价格（或者近期月份合约价格高于远期月份合约价格），基差为正值。
出现这种情况有两个原因：一个对某种商品的需求非常迫切，远大于产量及库存量；二是预计将来该商品的供给会大幅度增加。
正向市场也叫正常市场，即在正常情况下，期货价格高于实货价格（或者合约价格低于远期月份合约价格），基差为负值。
正向市场分为两种情况，一是期货价格高于现货价格，二是远期合约价格高于近期合约价格。因为期货市场多了未来的持有成本，理论上期货价格应该高于现货价格，远期合约的价格也相应高于近期合约的价格。正向市场是套期保值交易的理想环境。

*套期保值指在期货市场上买入（或卖出）与现货市场交易方向相反、数量相等的同种商品的期货合约，进而无论现货供应市场价格怎样波动，最终都能取得在一个市场上亏损的同时在另一个市场盈利的结果，并且亏损额与盈利额大致相等，从而达到规避风险的目的。
