#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLES: PortfolioOptimization
#+DATE: <2017-07-05 Wed>
#+AUTHORS: weiwu
#+EMAIL: victor.wuv@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)

[[file:../CS/Python/py4fi/Optimization.html][PortfolioOptimization]]
* Portfolio Optimization
- risk parity portfolios (Roncalli, 2013)
- Black–Litterman portfolios (Black and Litterman, 1992)
- log-optimal portfolios (Cover and Ordentlich, 1996)
- conditional value at risk (cVaR) and coherent risk measures for portfolios (Rockafellar and Uryasev, 2000)

* Basics
** Quadratic function
In algebra, a quadratic function, a quadratic polynomial, a polynomial of degree 2, or simply a quadratic, is a polynomial function in one or more variables in which the highest-degree term is of the second degree. For example, a quadratic function in three variables x, y, and z contains exclusively terms x2, y2, z2, xy, xz, yz, x, y, z, and a constant:

$$
{\displaystyle f(x,y,z)=ax^{2}+by^{2}+cz^{2}+dxy+exz+fyz+gx+hy+iz+j,} f(x,y,z)=ax^{2}+by^{2}+cz^{2}+dxy+exz+fyz+gx+hy+iz+j,
with at least one of the coefficients a, b, c, d, e, or f of the second-degree terms being non-zero.
$$
** Quadratic programming
- Quadratic programming (QP) is the process of solving a special type of mathematical optimization problem—specifically, a (linearly constrained) quadratic optimization problem, that is, the problem of optimizing (minimizing or maximizing) a quadratic function of several variables subject to linear constraints on these variables. Quadratic programming is a particular type of nonlinear programming.
** Nonlinear programming
the process of solving an optimization problem defined by a system of equalities and inequalities, collectively termed constraints, over a set of unknown real variables, along with an objective function to be maximized or minimized, where some of the constraints or the objective function are nonlinear.
** Equality constraints
Quadratic programming is particularly simple when Q is positive definite and there are only equality constraints; specifically, the solution process is linear. By using Lagrange multipliers and seeking the extremum of the Lagrangian, it may be readily shown that the solution to the equality constrained problem

$$
{\displaystyle {\text{Minimize}}\quad {\tfrac {1}{2}}\mathbf {x} ^{\mathrm {T} }Q\mathbf {x} +\mathbf {c} ^{\mathrm {T} }\mathbf {x} } {\text{Minimize}}\quad {\tfrac {1}{2}}\mathbf {x} ^{\mathrm {T} }Q\mathbf {x} +\mathbf {c} ^{\mathrm {T} }\mathbf {x}
{\displaystyle {\text{subject to}}\quad E\mathbf {x} =\mathbf {d} } {\text{subject to}}\quad E\mathbf {x} =\mathbf {d}
$$
is given by the linear system

$$
{\displaystyle {\begin{bmatrix}Q&-E^{T}\\E&0\end{bmatrix}}{\begin{bmatrix}\mathbf {x} \\\lambda \end{bmatrix}}={\begin{bmatrix}-\mathbf {c} \\\mathbf {d} \end{bmatrix}}} {\displaystyle {\begin{bmatrix}Q&-E^{T}\\E&0\end{bmatrix}}{\begin{bmatrix}\mathbf {x} \\\lambda \end{bmatrix}}={\begin{bmatrix}-\mathbf {c} \\\mathbf {d} \end{bmatrix}}} $$
where ${\displaystyle \lambda } \lambda$  is a set of Lagrange multipliers which come out of the solution alongside ${\displaystyle \mathbf {x} } \mathbf {x}$ .



OLS assumptions:
- Linear in Parameters
- Random Sample of n Observations
- Zero Conditional Mean
- No Perfect Collinearity
- Homoskedasticity

Pitfall of Modern Portfolio Theory(MPT):
- It is based on the historical return performance. If the political visk shows up or the fund changes policy or manager, the corporate or the fund performance may change.

Black–Litterman model:
It is a mathematical model for portfolio allocation developed in 1990 at Goldman Sachs by Fischer Black and Robert Litterman, and published in 1992. It seeks to overcome problems that institutional investors have encountered in applying modern portfolio theory in practice, although the covariances of a few assets can be adequately estimated, it is difficult to come up with reasonable estimates of expected returns. The model starts with the equilibrium assumption that the asset allocation of a representative agent should be proportional to the market values of the available assets, and then modifies that to take into account the 'views' (i.e., the specific opinions about asset returns) of the investor in question to arrive at a bespoke asset allocation.
* Sparse Markowitz Portfolios

* Mean-Reverting Portfolios

* Active portfolio management

** overview
Modern portfolio theory looks at total risk and total return.

The institutional investor cares about active risk and active return.
For that reason, we will concentrate on the more general problem of managing relative to a benchmark.
This focus on active management arises for several *reasons*:

*** risk aversion from unknown categories.
Clients can clump the large number of investment advisers into recognizable categories. With the advisers thus pigeonholed, the client (or consultant) can restrict searches and peer comparisons to pigeons in the same hole.

*** tracking the benchmark
The benchmark acts as a set of instructions from the fund sponsor, as principal, to the investment manager, as agent. The benchmark defines the manager’s investment neighborhood. Moves away from the benchmark carry substantial investment and business risk.

*** easy tracking for management
Benchmarks allow the trustee or sponsor to manage the aggregate portfolio without complete knowledge of the holdings of each manager. The sponsor can manage a mix of benchmarks, keeping the “big picture.""

* Portfolio Construction

** input:
- the current portfolio(with certainty)
- alphas(often unreasonable and subject to hidden biases)
- covariance estimates(noisy estimates)
- transactions cost estimates(noisy estimates)
- an active risk aversion(self-biased)
** constraints
*We can replace any portfolio construction process, regardless of its sophistication, by a process that first refines the alphas and then uses a simple unconstrained mean/variance optimization to determine the active positions.*
*** alpha constraint
- most institutional portfolio managers do not take short positions and limit the amount of cash in the portfolio.
- Others may restrict asset coverage because of requirements concerning liquidity, self-dealing, and so on.
- A manager may require that the portfolio be neutral across economic sectors or industries.
- The manager may limit individual stock positions to ensure diversification of the active bets.
- The manager may want to avoid any position based on a forecast of the benchmark portfolio’s performance.
- portfolio holdings cannot exceed benchmark holdings by more than 5%.
**** Scale the Alphas
$$\alpha=volatility*IC*score$$
**** Trim Alpha Outliers
**** Neutralization
**** Risk-Factor-Neutral Alphas
*** risk aversion

*** transaction cost
