#+SETUPFILE: ../configOrg/level1.org
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLES: PortfolioOptimization
#+DATE: <2017-07-05 Wed>
#+AUTHORS: weiwu
#+EMAIL: victor.wuv@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)

[[file:../CS/Python/py4fi/Optimization.html][PortfolioOptimizationJupyterProgramming]]

[[file:../CS/Python/py4fi/PortfolioOptimization.html][PortfolioOptimizationReadMe]]

* Portfolio Optimization objective functions
- risk parity portfolios (Roncalli, 2013)
- Black–Litterman portfolios (Black and Litterman, 1992)
- log-optimal portfolios (Cover and Ordentlich, 1996)
- conditional value at risk (cVaR) and coherent risk measures for portfolios (Rockafellar and Uryasev, 2000)

* Basics
** Risk aversion parameter
The weight vector that maximizes the expected portfolio growth rate E log(1 + Rtp) (subject to 1T w = 1, w ≥ 0) is called the Kelly optimal portfolio or log-optimal portfolio. Using the quadratic approximation of the logarithm log(1 + a) ≈ a − (1/2)a2 we obtain
$$E[log(1 + Rtp)] ≈ E[Rtp − (1/2)(Rtp)2]
= µT w − (1/2)wT (Σ + µµT )w$$,

where µ = Ert and Σ = E(rt−µ)(rt−µ)T are the mean and covariance of the return rt.
** alpha
Alpha is used to determine by how much the realized return of the portfolio varies from the required return, as determined by CAPM.
$$\alpha = R_{portfolio} - [R_f + (R_m - R_f)\beta]$$
** Quadratic function
In algebra, a quadratic function, a quadratic polynomial, a polynomial of degree 2, or simply a quadratic, is a polynomial function in one or more variables in which the highest-degree term is of the second degree. For example, a quadratic function in three variables x, y, and z contains exclusively terms x2, y2, z2, xy, xz, yz, x, y, z, and a constant:

$$
{\displaystyle f(x,y,z)=ax^{2}+by^{2}+cz^{2}+dxy+exz+fyz+gx+hy+iz+j,} f(x,y,z)=ax^{2}+by^{2}+cz^{2}+dxy+exz+fyz+gx+hy+iz+j,$$
with at least one of the coefficients a, b, c, d, e, or f of the second-degree terms being non-zero.

** Quadratic programming
- Quadratic programming (QP) is the process of solving a special type of mathematical optimization problem—specifically, a (linearly constrained) quadratic optimization problem, that is, the problem of optimizing (minimizing or maximizing) a quadratic function of several variables subject to linear constraints on these variables. Quadratic programming is a particular type of nonlinear programming.
** Nonlinear programming
the process of solving an optimization problem defined by a system of equalities and inequalities, collectively termed constraints, over a set of unknown real variables, along with an objective function to be maximized or minimized, where some of the constraints or the objective function are nonlinear.
** Equality constraints
Quadratic programming is particularly simple when Q is positive definite and there are only equality constraints; specifically, the solution process is linear. By using Lagrange multipliers and seeking the extremum of the Lagrangian, it may be readily shown that the solution to the equality constrained problem
$${\text{Minimize}}\quad {\tfrac {1}{2}}\mathbf {x} ^{\mathrm {T} }Q\mathbf {x} +\mathbf {c} ^{\mathrm {T} }\mathbf {x}
{\text{subject to}}\quad E\mathbf {x} =\mathbf {d}$$

is given by the linear system

$${\begin{bmatrix}Q&E^{T}\\E&0\end{bmatrix}}{\begin{bmatrix}\mathbf {x} \\\lambda \end{bmatrix}}={\begin{bmatrix}-\mathbf {c} \\\mathbf {d} \end{bmatrix}}$$
where ${\displaystyle \lambda }$  is a set of Lagrange multipliers which come out of the solution alongside ${\displaystyle \mathbf {x} }$ .
** Regime shifts


OLS assumptions:
- Linear in Parameters
- Random Sample of n Observations
- Zero Conditional Mean
- No Perfect Collinearity
- Homoskedasticity

Pitfall of Modern Portfolio Theory(MPT):
- It is based on the historical return performance. If the political visk shows up or the fund changes policy or manager, the corporate or the fund performance may change.

* Sparse Markowitz Portfolios

* Mean-Reverting Portfolios

* Active portfolio management

** overview
Modern portfolio theory looks at total risk and total return.

The institutional investor cares about active risk and active return.
For that reason, we will concentrate on the more general problem of managing relative to a benchmark.
This focus on active management arises for several *reasons*:

*** risk aversion from unknown categories.
Clients can clump the large number of investment advisers into recognizable categories. With the advisers thus pigeonholed, the client (or consultant) can restrict searches and peer comparisons to pigeons in the same hole.

*** tracking the benchmark
The benchmark acts as a set of instructions from the fund sponsor, as principal, to the investment manager, as agent. The benchmark defines the manager’s investment neighborhood. Moves away from the benchmark carry substantial investment and business risk.

*** easy tracking for management
Benchmarks allow the trustee or sponsor to manage the aggregate portfolio without complete knowledge of the holdings of each manager. The sponsor can manage a mix of benchmarks, keeping the “big picture.""

* Exceptional Return, benchmarks and value added
The CAPM provides consensus expected returns. A multiple-factor model can help to control risk.

accurate forecasts of expected return.
a riskfree component (the time premium), a benchmark component$\beta_n \mu_B$  (the risk premium), a benchmark timing component$\beta_n \delta f_B$ (exceptional benchmark return), and an alpha (expected residual return). If Rn is the total return on asset n.
$$E{R_n} = 1 + i_F + \beta_n \mu_B + \beta_n \delta f_B + \alpha_n$$
- $\beta_n = \frac{Cov{r_n,r_B}}{Var{r_B}}$
- The Risk Premium $\beta_n \mu_B$
The expected excess return on the benchmark, $\mu_B$, is usually estimated by analysts as a very long run (70+ years) average (although other estimation methods are common). A number between 3 and 7 percent per annum is reasonable for most equity markets.
- Exceptional Benchmark return $\beta_n \Delta f_B$
$\Delta f_B$ is your measure of that difference between the expected excess return on the benchmark in the near future and the long-run expected excess return.
- $\alpha_n$
expected residual return, $\alpha_n = E{\Theta_n}.$
| parameters  | meaning                                                 |
|-------------+---------------------------------------------------------|
| $\beta_n$   | the forecast beta of the portfolio versus the benchmark |
| $r_f$       | risk-free return                                        |
| $\mu_B$     | benchmark return over the last period(monthly)          |
| $\Delta f_B$ | $r_p - r_f - \mu_B$                                     |
| f_b         | $\displaystyle\sum_{n} h_B(n)E{R_N}-(1+i_F)$            |

* Portfolio Construction

** input:
- the current portfolio(with certainty)
- alphas(often unreasonable and subject to hidden biases)
- covariance estimates(noisy estimates)
- transactions cost estimates(noisy estimates)
- an active risk aversion(self-biased)
** constraints
*We can replace any portfolio construction process, regardless of its sophistication, by a process that first refines the alphas and then uses a simple unconstrained mean/variance optimization to determine the active positions.*
*** alpha constraint
- most institutional portfolio managers do not take short positions and limit the amount of cash in the portfolio.
- Others may restrict asset coverage because of requirements concerning liquidity, self-dealing, and so on.
- A manager may require that the portfolio be neutral across economic sectors or industries.
- The manager may limit individual stock positions to ensure diversification of the active bets.
- The manager may want to avoid any position based on a forecast of the benchmark portfolio’s performance.
- portfolio holdings cannot exceed benchmark holdings by more than 5%.
**** Scale the Alphas
$$\alpha=volatility*IC*score$$
**** Trim Alpha Outliers
**** Neutralization
**** Risk-Factor-Neutral Alphas
**** For index-tracking portfolios
- Take advantage of ﬂexible options for risk control.
  - Minimize the tracking error of your portfolio in the objective or place a hard limit on tracking error using a risk constraint.
  - Use more than one risk model to incorporate several perspectives on risk.
  - Include risk elements that use more than one benchmark or model portfolio.
- Incorporate all the transaction-related costs that impact performance. The transaction cost types available in the optimizer can be used in any combination to accurately reﬂect overall costs.
  - Capture market impact using non-linear market-impact models (quadratic, 3/2, and 5/3 powers) or a piecewiselinear approximation.
  - Use the fully integrated Goldman Sachs Shortfall Model.
  - Include commissions and brokerage fees using linear costs.
- Place explicit limits on trading activity.
  - Limit overall portfolio turnover or limit turnover of a set of assets.
  - Place asset-specifc limits on trading; for example, limit trade size to a fraction of average daily volume.
- Control portfolio beta using Axioma-provided historical betas, predicted betas computed relative to any benchmark you choose, or betas you supply.
- Limit the number of names held or traded
**** For actively managed portfolios…
In addition to the risk and transaction cost controls available for passive portfolio management, the modeling library contains many options designed to get the most from your alpha signal.
• Augment your risk control using the Alpha Factor. The Alpha Factor compensates for components of your alpha signal that are not included in the risk model, providing more accurate predicted risk estimates.
• Limit risk contributions at the factor or asset level.
• Use Robust Optimization to explicitly incorporate uncertainty in your alpha estimates.
• Incorporate additional tilts in your objective. Tilts can be implemented on any factor, including risk factors, factors from one of Axioma’s factor libraries, or user-supplied factors.
• Prevent small positions and small trades with threshold constraints.
*** risk aversion

*** transaction cost

**** on stock side
- Transactions costs increase with trade size and the desire for quick execution, which help to identify the manager as an informed trader and require increased inventory risk by the liquidity supplier.
- Transactions costs are difficult to measure. At the same time, accurate estimates of transactions costs, especially distinctions in transactions costs among different stock trades, can significantly affect realized value added.
- Transactions costs lower value added, but you can often achieve at least 75 percent of the value added with only half the turnover (and half the transactions costs). You can do better by distinguishing stocks by their transactions costs.
- Trading is itself a portfolio optimization problem, distinct from the portfolio construction problem. Optimal trading can lower transactions costs, though at the expense of additional short-term risk.
- There are several options for trade implementation, with rules of thumb on which to use when.
  - VWAP.
  - BARRA model.

**** on portfolio side
- construct portfolio relative to industry neutral with categories.
** SCREENS
- Rank the stocks by alpha.
- Choose the first 50 stocks (for example).
- Equal-weight (or capitalization-weight) the stocks.
  - rebalancing:
    - divide the stocks into three categores, top 40, next 60, remaining 100.
    - buy any stocks on the top 40 not in the portfolio.
    - sell any stocks on the bottom 100 in the portfolio.
    - holding any stocks on the middle in the portfolio.
  - pros:
    - The screen enhances alphas by concentrating the portfolio in the high-alpha stocks.
    - It strives for risk control by including a sufficient number of stocks (50 in the example) and by weighting them to avoid concentration in any single stock.
    - Transactions costs are limited by controlling turnover through judicious choice of the size of the buy, sell, and hold lists.
  - cons:
    - They ignore all information in the alphas apart from the rankings.
    - They do not protect against biases in the alphas.

** Stratification
- splitting the list of followed stocks into categories.
- classify the stocks in each sector by size: big, medium, and small.
- industry neutral.

** comparison with asset selection and asset allocation
The result is that portfolios constructed using returns-based analysis are very close to mean/variance portfolios, although they require much more effort to construct.
** solution
- placing limits on active stock positions.
- limiting turnover.
- constraining holdings in certain categories of stocks to match the benchmark holdings.
* Asset Allocation
Asset allocation comes in several varieties: strategic versus tactical, and domestic versus global.

The process of selecting a target asset allocation is called strategic asset allocation.

The variation in asset allocation around that target is called tactical asset allocation.
** tactical asset allocation
- stocks
- bonds
- cash
** asset allocation strategies is a three-step process:
- forecasting returns
- building portfolios
- analyzing out-of-sample performance.
* Black litterman model step-by-step
** Introduction
The Black-Litterman model uses a *Bayesian* approach to combine the subjective views of an investor regarding the expected returns of one or more assets with the market equilibrium vector of expected returns (the prior distribution) to form a new, mixed estimate of expected returns.

Black–Litterman model is a mathematical model for portfolio allocation developed in 1990 at Goldman Sachs by Fischer Black and Robert Litterman, and published in 1992. It seeks to overcome problems that institutional investors have encountered in applying modern portfolio theory in practice, although the covariances of a few assets can be adequately estimated, *it is difficult to come up with reasonable estimates of expected returns*. The model starts with the equilibrium assumption that the asset allocation of a representative agent should be proportional to the market values of the available assets, and then modifies that to take into account the 'views' (i.e., the specific opinions about asset returns) of the investor in question to arrive at a bespoke asset allocation.

Black–Litterman overcame this problem by not requiring the user to input estimates of expected return; instead it assumes that the initial expected returns are whatever is required so that the equilibrium asset allocation is equal to what we observe in the markets. *The user is only required to state how his assumptions about expected returns differ from the market's and to state his degree of confidence in the alternative assumptions*. From this, the Black–Litterman method computes the desired (mean-variance efficient) asset allocation.

In general, when there are portfolio constraints - for example, when short sales are not allowed
- the easiest way to find the optimal portfolio is to use the Black–Litterman model to generate the expected returns for the assets,
- and then use a mean-variance optimizer to solve the constrained optimization problem.
** Problem of mean-variance optimization
- Extreme long or short positions
It could bring extreme long or short positions without constraint(excluding risk exposure constraint, weight constraint).

- Heavy weight on a small number of assets
When subject to a long only constraint, portfolios will concentrate in a relatively small number of assets.
- Importance of expected return
A small increase in the expected return of one of the portfolio's assets can force half of the assets from the portfolio.

*** reverse optimization to mitigate this problem
$$\Pi = \lambda\Sigma\omega_{mkt}$$
where

$\Pi$ is the impolied excess equilibrium return vector(Nx1 vector);

$\lambda$ is the risk aversion coefficient, $\lambda=\frac{E(r)-r_f}{\sigma^2}$;

$\Sigma$ is the covariance matrix of excess returns(NxN matrix);

$\omega_{mkt}$ is the market capitalization asset weight(Nx1 vector).
** Black-Litterman model and the process of building the required inputs.
*** Black-Litterman model
**** Formula
$$E(R)=[(\tau\Sigma)^{-1}+P'\Omega^{-1}P]^{-1}[(\tau\Sigma)^{-1}\Pi+P'\Omega^{-1}P]$$
where

- $E(R)$
is the new(posterior) combined return vector(Nx1);

- $\tau$
is a scalar;

- $\Sigma$
is the covariance matrix of excess returns(NxN matrix);

- $P$
is a matrix that identifies the assets involved in the views(KxN);

- $\Omega$
is a diagonal covariance matrix of error terms from the expressed views representing the uncertainty in each view(KxK);

A view has the form $Q+\epsilon$.
$$\begin{bmatrix}
w1 & 0 & 0\\
0 & ... & 0\\
0 & 0 & w3
\end{bmatrix}$$

- $\Pi$
is the implied equilibrium return vector(Nx1);
$$\begin{cases}
Litterman & \text {percentage} \\
Satchell and Scowcroft & \text{ equal weight } \\
Thomas Idzorek & \text{ market capital weight }
\end{cases}$$
The relative weighting of each individual asset is proportional to the asset’s market capitalization divided by the total market capitalization of either the outperforming or underperforming assets of that particular view.

The net long positions less the net short positions equal 0.

Thus one can calculate the variance of each individual view portfolio $p_k\Sigma p'_k$.
- $Q$
is the view vector(Kx1);
**** Investor views
Absolute or relative manager views regarding the expected reutnr of some of the assets in the portfolio.

- absolute view:
Asset A will have an absolute excess return of x%;

- relative view 1:
Asset A will outperform/underperform asset B by xx basis point;

- relative view 2:
Assets A and B will outperform/underperform assets C and D by xx basis points; Equivallently a mini long/short portfolio including A and B vesus a mini short/long portfolio.
*** Inputs
- $\Omega$
- $Q$

** Implied confidence framework for the views
$\Omega$, which representing the uncertainty of the views, and $\tau$ are the most abstract mathematical parameters of this model.

how to specify a probability density function for each view?

*** Implied confidence levels
$$\frac{
*** An intuitive approach
* NLP
- Hidden factor model
- portfolio optimization based on factor model
- non linear constrain on factor model

accounting formula production function, using unit conversion, to do mathematical analysis.

opinions/factors can be used as constraints on factors with hiden factor model.

such factor constraints can be used in Black-Litterman model.
